services:
  db:
    image: mysql 
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: viajesin
    volumes:
      - mysqldata:/var/lib/mysql
volumes:
  mysqldata:
