services:
  db:
    image: postgres:15.1-alpine
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: viajesin
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:

