name: CI

on: [push, pull_request]

env:
  DATABASE_URL: "https://fake.com"
  NEXT_PUBLIC_DISCORD_CLIENT_ID: "fake"
  DISCORD_CLIENT_SECRET: "fake"
  NEXTAUTH_URL: "https://fake.com"
  NEXTAUTH_SECRET: "fake"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install pnpm
      - uses: pnpm/action-setup@v2

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm typecheck

      - name: Lint
        run: pnpm lint

      - name: Print Environment Variable
        run: echo $MY_ENV_VAR
