name: CI

on: [push, pull_request]

env:
  DATABASE_URL: "https://fake.com"
  NEXT_PUBLIC_DISCORD_CLIENT_ID: "fake"
  DISCORD_CLIENT_SECRET: "fake"
  NEXTAUTH_URL: "https://fake.com"
  NEXTAUTH_SECRET: "fake"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: pnpm i

      - name: Typecheck
        run: pnpm typecheck

      - name: Lint
        run: pnpm lint

      - name: Print Environment Variable
        run: echo $MY_ENV_VAR
